# token은 CI에서 secrets.CODECOV_TOKEN으로 전달
codecov: {}

coverage:
    precision: 2
    round: down
    range: "50..100"

    status:
        project:
            default:
                target: auto
                threshold: 0.75
                informational: false

        patch:
            default:
                target: 85%
                informational: false

comment:
    layout: "reach, diff"
    behavior: default
    require_changes: true
    require_base: true
    require_head: true

ignore:
    - "**/tests/**"
    - "**/__tests__/**"
    - "**/dist/**"
    - "**/build/**"
    - "**/coverage/**"
    - "**/*.d.ts"
